apiVersion: mongodbatlas.jet.crossplane.io/v1alpha1
kind: AdvancedCluster
metadata:
  name: example-advanced-cluster
spec:
  forProvider:
    projectIdRef:
      name: example-project
    clusterType: REPLICASET
    name: example-advanced-cluster
    replicationSpecs:
    - regionConfigs:
      - electableSpecs:
        - instanceSize: M0
        providerName: TENANT
        backingProviderName: AWS
        regionName: US_EAST_1
        priority: 1
  providerConfigRef:
    name: default
